[build]
  publish = "."  # Directorio de archivos estáticos (HTML, CSS, JS)
  functions = "functions" # Directorio donde están las Netlify Functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["functions/certs/condusef-gob-mx-chain.pem"]